import 'package:hinario_para_criancas_ccb/models/Cards_Models/cards_models.dart';
import 'package:hinario_para_criancas_ccb/models/Question_Model/question_model.dart';
import 'package:logger/logger.dart';

class QuestionProvider {
  List<CardsModels> dataCards() {
    try {
      CardsModels historia = CardsModels(
          title: "História",
          image: "assets/images/historias.png",
          type: "historia");
      CardsModels perguntas = CardsModels(
          title: "Perguntas",
          image: "assets/images/question.png",
          type: "perguntas");
      CardsModels vamosBrincar = CardsModels(
          title: "Vamos Brincar",
          image: "assets/images/vamos_brincar.png",
          type: "vamosBrincar");
      List<CardsModels> data = [historia, perguntas, vamosBrincar];
      return data;
    } catch (e) {
      return [];
    }
  }

  List<QuestionModel> dataQuestions() {
    try {
      List<QuestionModel> totalQuestion = [];
      List question = [
        "Qual profeta que foi engolido por um grande peixe?",
        "Quem derrubou a muralha de Jericó?",
        "Qual o nome do gigante que Davi derrubou?",
        "Quantos discípulos Jesus tinha?",
        "Como se chamava o líder do egito?",
        "O que Davi fazia antes de ser rei?",
        "Quem é considerado o homem mais forte da Bíblia?",
        "Quais foram os presentes que os reis magos ofereceram a Jesus?",
        "Que instrumento Josué usou para derrubar as muralhas de Jericó?",
        "Qual o nome do último livro da Bíblia?",
        "Quem era considerado o homem mais sábio do mundo?",
        'Quem foi "o pai da grande nação"?',
        "Quem avisou Maria que ela teria um filho?",
        "Por que Sadraque, Mesaque e Abede-nego foram jogados na fornalha ardente?",
        "Qual o nome do anjo que apareceu a Maria?",
        "O que representa o vinho da ceia do Senhor?",
        "O que representa o pão da ceia do Senhor?",
        "O que o Senhor Jesus pediu para a samaritana?",
        "Quem foi colocado em um cestinho e jogado em um rio ainda bebê?",
        "Quem foi o profeta que foi lançado nas covas dos Leões?",
        "Qual era a profissão de José, pai de Jesus?",
        "Depois do dilúvio, qual o sinal que Jesus fez simbolizando a promessa de não mais acabar o mundo com água?",
        "Quem foi chamado por Deus enquanto estava dormindo?",
        "Jesus disse que o reino de Deus pertence as crianças. Em qual livro da Bíblia está escrito?",
        "Qual era o nome do filho de Abraão",
        "O que Jeuss disse sobre quantas vezes devemos perdoar?",
        "Qual era o nome da cidade que Deus mandou Jonas pregar?",
        "Jacó gostava muito de José. O que ele deu de presente para seu filho?",
        "Quando Daniel foi lançado na covas dos leões o que aconteceu?",
        "Quando pedro cortou a orelha do soldado, o que Jesus fez?",
        "Davi foi rei de qual nação?",
        "Qual era o nome do rei da Babilônia?",
        "Quem era o rei que perseguia Davi?",
        "Quem é o homem mais velho da Bílblia?",
        "Qual era o primeiro nome de Paulo?",
        "O que significa Emanuel segundo a palavra de Deus?",
        "Jesus foi crucificado junto de quantas pessoas?",
        "Qual livro foi escrito por Salomão?",
        "Os discipulos estavam no mar desesperados numa tempestade, o que Jesus fez?",
        "Qual era o nome dos religiosos que perseguiam Jesus?",
        'Jesus disse que "quem Aceitá-lo e se batizar será..." ',
        "Qual o nome da jovem judia que casou-se com o rei da Pérsia e salvou o povo judeu do exterminio?",
        "Qual rei era jovem, bonito e alto?",
        "Qual animal não foi citado na Biblia?",
        "Qual era a idade de Jesus quando realizou o seu primeiro milagre?",
        "Qual jovem da Bíblia se tornou rainha em um concurso de beleza?",
        "Qual rei entrou na cidade dançando e cantando?",
        "Oh quão bom e quão suave é que os irmãos vivam em união, qual Salmos está escrito este versiculo?",
        "Qual o nome do rei que reuniu esforços para tentar matar Jesus?",
      ];

      List response = [
        "Jonas",
        "Josué",
        "Golias",
        "12",
        "Faraó",
        "Era um pastor de ovelhas",
        "Sansão",
        "Ouro, incenso e mirra",
        "Trombeta",
        "Livro de Apocalipse",
        "Salomão",
        "Abraão",
        "Um anjo",
        "Negaram a adorar outros deuses",
        "Gabriel",
        "O sangue de Cristo",
        "O corpo de Cristo",
        "Pediu água para beber",
        "Moisés",
        "Daniel",
        "Carpinteiro",
        "Um Arco-Íris",
        "Samuel",
        "Livro de Mateus",
        "Isaque",
        "Devemos perdoar 70 x 7",
        "Nínive",
        "Uma túnica",
        "O anjo fechou a boca dos leões",
        "Colocou a orelha de volta no lugar",
        "Israel",
        "Nabucodonosor",
        "Saul",
        "Matusalém",
        "Saulo",
        "Deus conosco",
        "Foi crucificado entre dois ladrões",
        "Provérvios",
        "Mandou o mar se acalmar",
        "Fariseus",
        "Salvo",
        "Ester",
        "Saul",
        "O gato",
        "30 anos",
        "Ester",
        "Davi",
        "Salmos",
        "Rei Herodes"
      ];

      List primaryError = [
        "Elias",
        "Calebe",
        "Caim",
        "10",
        "César",
        "Era um pescador",
        "Esaú",
        "Prata, bronze e vinho",
        "Harpa",
        "Livro de Gênesis",
        "Roboão",
        "Jacó",
        "Um profeta",
        "Rejeitaram a liberdade",
        "Rafael",
        "A água da vida",
        "A palavra de Cristo",
        "Pediu pão para comer",
        "Noé",
        "Jeremias",
        "Pescador",
        "Uma estrela",
        "Elias",
        "Livro de Marcos",
        "Jacó",
        "Devemos corrigir",
        "Babel",
        "Uma coroa",
        "O anjo quebrou as correntes",
        "Repreendeu a ovelha",
        "Canaã",
        "Hamã",
        "Absalão",
        "Noé",
        "Herodes",
        "Deus entre nós",
        "Foi sepultado entre dois profetas",
        "Salmos",
        "Mandou a chuva parar",
        "Saduceus",
        "Redimido",
        "Débora",
        "Josias",
        "O cordeiro",
        "40 anos",
        "Rute",
        "Saul",
        "Cantares",
        "Rei Acabe"
      ];

      List secondError = [
        "Ezequiel",
        "Gideão",
        "Amaleque",
        "7",
        "Pilatos",
        "Era um ferreiro",
        "Noé",
        "Ouro, mirra e azeite",
        "Flauta",
        "Livro de Êxodo",
        "Absalão",
        "Enoque",
        "Um sacerdote",
        "Aceitaram riquezas",
        "Miguel",
        "O pão da vida",
        "A luz de Cristo",
        "Pediu vinho para beber",
        "Abraão",
        "Ezequiel",
        "Pastor",
        "Um trovão",
        "Eli",
        "Livro de Lucas",
        "Jafé",
        "Devemos retribuir",
        "Canaã",
        "Uma espada",
        "O anjo iluminou a caverna",
        "Sacrificou a ovelha",
        "Egito",
        "Xerxes",
        "Davi",
        "Enos",
        "Filipe",
        "Deus em nós",
        "Foi enterrado com um rei",
        "Eclesiastes",
        "Mandou a tempestade voltar",
        "Essênios",
        "Justificado",
        "Sara",
        "Ezequias",
        "A ovelha",
        "20 anos",
        "Ana",
        "Salomão",
        "Provérbios",
        "Rei Salomão"
      ];

      List terciaryError = [
        "Malaquias",
        "Micaías",
        "Abimeleque",
        "5",
        "Herodes",
        "Era um agricultor",
        "Abner",
        "Perfume, incenso e prata",
        "Tambor",
        "Livro de Levítico",
        "Josias",
        "Noé",
        "Um rei",
        "Fugiram para o deserto",
        "Uriel",
        "O vinho de Cristo",
        "O espírito de Cristo",
        "Pediu descanso",
        "Elias",
        "Amós",
        "Pedreiro",
        "Um raio",
        "Davi",
        "Livro de João",
        "Esaú",
        "Devemos lembrar",
        "Jericó",
        "Um cajado",
        "O anjo dispersou os leões",
        "Levou a ovelha para outro pasto",
        "Assíria",
        "Acabe",
        "Salomão",
        "Jared",
        "Marcos",
        "Deus por nós",
        "Foi julgado com dois sacerdotes",
        "Cantares",
        "Mandou o vento soprar",
        "Levitas",
        "Ressuscitado",
        "Rebeca",
        "Jeroboão",
        "O boi",
        "25 anos",
        "Naomí",
        "Josias",
        "Eclesiastes",
        "Rei Davi"
      ];
      //TODO: FAZER LISTA DE REFERENCIAS
      List references = [
        "Jonas 1:17",
        "Josué 6:1-27",
        "I Samuel 17:4",
        "Mateus 10:1",
        "Gênesis 41:14",
        "I Samuel 16:11-13",
        "Juízes 14:5-6",
        "Mateus 2:11",
        "Josué 6:20",
        "Apocalipse",
        "I Reis 4:30",
        "Gênesis 18:18",
        "Lucas 1:28-29",
        "Daniel 3:12",
        "Lucas 1:26-27",
        "I Corintios 11:25",
        "I Corintios 11:24",
        "João 4:4-42",
        "Exodo 2:3",
        "Daniel 6:16",
        "Mateus 13:55",
        "Gênises 9:16",
        "I Samuel 3:10",
        "Mateus 19:14",
        "Gênesis 17:19",
        "Mateus 18:22",
        "Jonas 3:2",
        "Gênesis 37:3",
        "Daniel 6:22",
        "Lucas 22:51",
        "II Samuel 5:1-4",
        "II Reis 24:1-2",
        "I Samuel 19:1",
        "Gênesis 5:27",
        "Atos 8:3",
        "Mateus 1:23",
        "Mateus 27:28",
        "Provérbios 1:1",
        "Marcos 4:39",
        "Mateus 3:7",
        "Marcos 16:16",
        "Ester 8",
        "I Samuel 9:2",
        "",
        "João 2:11",
        "Ester 2",
        "II Samuel 6:5",
        "Salmos 133:1",
        "Mateus 2"
      ];

      for (int i = 0; i < question.length; i++) {
        totalQuestion.add(
          QuestionModel(
              number: (i + 1).toString(),
              question: question[i],
              response: response[i],
              references: references[i],
              primaryError: primaryError[i],
              secondError: secondError[i],
              terciaryError: terciaryError[i]),
        );
      }
      Logger().e(totalQuestion);
      return totalQuestion;
    } catch (e) {
      return [];
    }
  }
}
